bind 127.0.0.1 ::1
protected-mode yes
port 6380
tcp-backlog 511
timeout 0
tcp-keepalive 300
supervised systemd
daemonize no
loglevel notice
databases 16
dir /var/lib/unikorn-redis
dbfilename dump.rdb
appendonly yes
appenddirname appendonlydir
appendfsync everysec
save 3600 1 300 100 60 10000
