"""empty message

Revision ID: 16fc8b09ac36
Revises: e1e1f8bc2a08
Create Date: 2025-09-15 18:46:57.729477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16fc8b09ac36'
down_revision = 'e1e1f8bc2a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('duration_estimate', sa.String(length=50), nullable=True),
    sa.Column('team_size_min', sa.Integer(), nullable=True),
    sa.Column('team_size_max', sa.Integer(), nullable=True),
    sa.Column('looking_for_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('interest_count', sa.Integer(), nullable=False),
    sa.Column('collaboration_method', sa.String(length=50), nullable=True),
    sa.Column('meeting_frequency', sa.String(length=50), nullable=True),
    sa.Column('communication_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('team_size_min <= team_size_max', name='check_team_size'),
    sa.CheckConstraint('view_count >= 0 AND interest_count >= 0', name='check_positive_counts'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_active', ['is_deleted', 'status'], unique=False)
        batch_op.create_index('idx_projects_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_projects_difficulty', ['difficulty_level'], unique=False)
        batch_op.create_index('idx_projects_status', ['status'], unique=False)
        batch_op.create_index('idx_projects_type', ['project_type'], unique=False)
        batch_op.create_index('idx_projects_user_id', ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('thrust', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=True),
    sa.Column('preferred_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('contact_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_user_profiles_active', ['is_active'], unique=False)
        batch_op.create_index('idx_user_profiles_experience', ['experience_level'], unique=False)
        batch_op.create_index('idx_user_profiles_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_user_profiles_user_id')
        batch_op.drop_index('idx_user_profiles_experience')
        batch_op.drop_index('idx_user_profiles_active')

    op.drop_table('user_profiles')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_user_id')
        batch_op.drop_index('idx_projects_type')
        batch_op.drop_index('idx_projects_status')
        batch_op.drop_index('idx_projects_difficulty')
        batch_op.drop_index('idx_projects_created_at')
        batch_op.drop_index('idx_projects_active')

    op.drop_table('projects')
    # ### end Alembic commands ###
