"""add last_active_at to users

Revision ID: 26114cd79af5
Revises: 46a8510e7c33
Create Date: 2025-06-05 17:28:48.979609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26114cd79af5'
down_revision = '46a8510e7c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active_at')

    # ### end Alembic commands ###
