"""empty message

Revision ID: 46a8510e7c33
Revises: 7ddb3557965d
Create Date: 2025-06-05 03:30:05.641227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a8510e7c33'
down_revision = '7ddb3557965d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
