"""empty message

Revision ID: 5202003d1ec0
Revises: b79b55da2342
Create Date: 2026-04-20 17:24:04.665654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5202003d1ec0'
down_revision = 'b79b55da2342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gugu_messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'gugu_messages', ['reply_to_message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gugu_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
