"""empty message

Revision ID: 71258dd20b96
Revises: b47e6b06d0a5
Create Date: 2026-04-15 22:00:39.444097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71258dd20b96'
down_revision = 'b47e6b06d0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_identity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_identities', ['display_identity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('display_identity_id')

    # ### end Alembic commands ###
