"""empty message

Revision ID: 7ddb3557965d
Revises: fcb7600cb027
Create Date: 2025-06-04 20:21:59.508074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddb3557965d'
down_revision = 'fcb7600cb027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity IS NULL OR capacity > 0', name='valid_capacity'),
    sa.CheckConstraint('credits > 0', name='valid_credits'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('idx_courses_code_active', ['code'], unique=False, postgresql_where=sa.text('is_active IS TRUE AND is_deleted IS FALSE'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('idx_courses_code_active', postgresql_where=sa.text('is_active IS TRUE AND is_deleted IS FALSE'))

    op.drop_table('courses')
    # ### end Alembic commands ###
