"""make tagtype table

Revision ID: 953e7504e161
Revises: 7658cd1e9afd
Create Date: 2025-04-05 18:05:03.149049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '953e7504e161'
down_revision = '7658cd1e9afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tag_types', ['tag_type_id'], ['id'])
        batch_op.drop_column('tag_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_type', postgresql.ENUM('system', 'user', name='tag_type_enum'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tag_type_id')

    op.drop_table('tag_types')
    # ### end Alembic commands ###
