"""empty message

Revision ID: 9e590f09c480
Revises: be83300befac
Create Date: 2025-08-16 21:49:46.399099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e590f09c480'
down_revision = 'be83300befac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_expires_at')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('email_verification_expires_at')
        batch_op.drop_column('email_verification_code')

    # ### end Alembic commands ###
