"""empty message

Revision ID: afa87f14e7ec
Revises: 26114cd79af5
Create Date: 2025-06-12 14:30:17.422757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa87f14e7ec'
down_revision = '26114cd79af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'files', ['profile_picture_file_id'], ['id'])
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile_picture_file_id')

    # ### end Alembic commands ###
