"""empty message

Revision ID: b79b55da2342
Revises: 71258dd20b96
Create Date: 2026-04-16 12:51:36.912018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79b55da2342'
down_revision = '71258dd20b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_contest_submissions_user_track'))
        batch_op.create_unique_constraint('uq_contest_submissions_user_track', ['user_id', 'track'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest_submissions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_contest_submissions_user_track', type_='unique')
        batch_op.create_index(batch_op.f('uq_contest_submissions_user_track'), ['user_id', 'track'], unique=True)

    # ### end Alembic commands ###
