"""identity

Revision ID: e1e1f8bc2a08
Revises: c6b065474532
Create Date: 2025-09-05 02:33:08.138854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1e1f8bc2a08'
down_revision = 'c6b065474532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('identity_type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verification_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'revoked')", name='ck_user_identities_status'),
    sa.ForeignKeyConstraint(['identity_type_id'], ['identity_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'identity_type_id', name='uq_user_identity_type')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index('idx_user_identities_status', ['status'], unique=False)
        batch_op.create_index('idx_user_identities_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_identity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_identities', ['display_identity_id'], ['id'])

    with op.batch_alter_table('gugu_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_identity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_identities', ['display_identity_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_identity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_identities', ['display_identity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('display_identity_id')

    with op.batch_alter_table('gugu_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('display_identity_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('display_identity_id')

    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index('idx_user_identities_user_status')
        batch_op.drop_index('idx_user_identities_status')

    op.drop_table('user_identities')
    op.drop_table('identity_types')
    # ### end Alembic commands ###
