"""empty message

Revision ID: fcb7600cb027
Revises: e2cd7dc52e64
Create Date: 2025-04-19 19:29:28.606412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb7600cb027'
down_revision = 'e2cd7dc52e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('object_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_files_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_status'))
        batch_op.drop_index(batch_op.f('ix_files_file_type'))
        batch_op.drop_index(batch_op.f('ix_files_entity_type'))
        batch_op.drop_index(batch_op.f('ix_files_entity_id'))
        batch_op.alter_column('file_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('object_name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
