name: Deploy to Dev Server (SocketIO)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.DEV_USER }}
        key: ${{ secrets.DEV_SSH_KEY }}
        script: |
          echo "Start deploying..."
          cd /data/dev_unikorn/back-end/
          git pull origin main
          echo "Pulled latest code."

          echo "Installing python packages..."
          source venv/bin/activate
          pip install -r requirements.txt --timeout 600
          echo "python packages installed."

          echo "performing database migrations..."
          flask db migrate
          flask db upgrade
          echo "database migrations completed."
          
          echo "initializing database with predefined data..."
          python -m app.scripts.init_db
          echo "database initialization completed."

          echo "Creating required directories for SocketIO..."
          sudo mkdir -p /var/log/gunicorn /var/run/gunicorn
          sudo chown $(whoami):$(whoami) /var/log/gunicorn /var/run/gunicorn || true

          echo "Checking if service needs SocketIO update..."
          if ! sudo systemctl cat dev-unikorn-api.service | grep -q "gunicorn.conf.py"; then
            echo "Updating service for SocketIO support..."
            
            # Create service override
            sudo mkdir -p /etc/systemd/system/dev-unikorn-api.service.d
            sudo tee /etc/systemd/system/dev-unikorn-api.service.d/socketio.conf > /dev/null <<EOF
          [Service]
          ExecStart=
          ExecStart=/data/dev_unikorn/back-end/venv/bin/gunicorn --config /data/dev_unikorn/back-end/gunicorn.conf.py wsgi:application
          WorkingDirectory=/data/dev_unikorn/back-end
          EOF
            
            sudo systemctl daemon-reload
            echo "Service updated for SocketIO support."
          else
            echo "Service already configured for SocketIO."
          fi

          sudo /usr/bin/systemctl restart dev-unikorn-api.service
          echo "server service restarted."

          # Wait and verify SocketIO is working
          sleep 5
          echo "Testing SocketIO endpoint..."
          if curl -f -I https://dev.unikorn.axfff.com/socket.io/ > /dev/null 2>&1; then
            echo "✅ SocketIO endpoint is working!"
          else
            echo "⚠️ SocketIO endpoint not responding, but deployment continued."
          fi

          echo "Deployment complete."